-- Tabela de biblioteca de ativos

CREATE TABLE IF NOT EXISTS public.library (
  id bigint generated by default as identity primary key,
  tenant_slug text not null,
  url text not null,
  type text not null default 'image',
  provider text not null default 'gdrive',
  task_id bigint null,
  title text null,
  tags text[] null,
  metadata jsonb null,
  created_at timestamptz default now()
);

CREATE INDEX IF NOT EXISTS library_tenant_idx
  ON public.library (tenant_slug);

CREATE INDEX IF NOT EXISTS library_created_at_idx
  ON public.library (created_at desc);
