-- Métricas reais de mídia por canal e mês (por tenant)

CREATE TABLE IF NOT EXISTS public.media_channel_metrics (
  id bigint generated by default as identity primary key,
  tenant_slug text not null,
  channel_id text not null,
  month text not null, -- formato YYYY-MM
  invest numeric(12,2),
  leads integer,
  vendas integer,
  revenue numeric(12,2),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

CREATE UNIQUE INDEX IF NOT EXISTS media_channel_metrics_unique
  ON public.media_channel_metrics (tenant_slug, channel_id, month);

CREATE INDEX IF NOT EXISTS media_channel_metrics_tenant_idx
  ON public.media_channel_metrics (tenant_slug);

ALTER TABLE public.media_channel_metrics ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "media_channel_metrics read" ON public.media_channel_metrics;
CREATE POLICY "media_channel_metrics read"
ON public.media_channel_metrics
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = media_channel_metrics.tenant_slug
  )
);

DROP POLICY IF EXISTS "media_channel_metrics insert" ON public.media_channel_metrics;
CREATE POLICY "media_channel_metrics insert"
ON public.media_channel_metrics
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = media_channel_metrics.tenant_slug
  )
);

DROP POLICY IF EXISTS "media_channel_metrics update" ON public.media_channel_metrics;
CREATE POLICY "media_channel_metrics update"
ON public.media_channel_metrics
FOR UPDATE
USING (
  EXISTS (
    SELECT 1
    FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = media_channel_metrics.tenant_slug
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = media_channel_metrics.tenant_slug
  )
);

DROP POLICY IF EXISTS "media_channel_metrics delete" ON public.media_channel_metrics;
CREATE POLICY "media_channel_metrics delete"
ON public.media_channel_metrics
FOR DELETE
USING (
  EXISTS (
    SELECT 1
    FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = media_channel_metrics.tenant_slug
  )
);
