CREATE TABLE IF NOT EXISTS public.studio_state_versions (
  id bigint generated by default as identity primary key,
  tenant_slug text not null,
  task_id bigint not null,
  studio_type text not null,
  label text,
  state jsonb not null,
  created_at timestamptz default now(),
  created_by uuid null
);

CREATE INDEX IF NOT EXISTS studio_state_versions_tenant_idx
  ON public.studio_state_versions (tenant_slug);

ALTER TABLE public.studio_state_versions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "studio_state_versions read" ON public.studio_state_versions;
CREATE POLICY "studio_state_versions read"
ON public.studio_state_versions FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = studio_state_versions.tenant_slug
  )
);

DROP POLICY IF EXISTS "studio_state_versions write" ON public.studio_state_versions;
CREATE POLICY "studio_state_versions write"
ON public.studio_state_versions FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = studio_state_versions.tenant_slug
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = studio_state_versions.tenant_slug
  )
);
