CREATE TABLE IF NOT EXISTS public.studio_states (
  id bigint generated by default as identity primary key,
  tenant_slug text not null,
  task_id bigint not null,
  studio_type text not null,
  state jsonb not null,
  updated_at timestamptz default now(),
  created_by uuid null,
  unique (tenant_slug, task_id, studio_type)
);

CREATE INDEX IF NOT EXISTS studio_states_tenant_idx
  ON public.studio_states (tenant_slug);

ALTER TABLE public.studio_states ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "studio_states read" ON public.studio_states;
CREATE POLICY "studio_states read"
ON public.studio_states FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = studio_states.tenant_slug
  )
);

DROP POLICY IF EXISTS "studio_states write" ON public.studio_states;
CREATE POLICY "studio_states write"
ON public.studio_states FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = studio_states.tenant_slug
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = studio_states.tenant_slug
  )
);
