-- Tabela suppliers (fornecedores) por tenant

CREATE TABLE IF NOT EXISTS public.suppliers (
  id bigint generated by default as identity primary key,
  tenant_slug text not null,
  name text not null,
  category text,
  specialty text,
  cnpj_cpf text,
  email text,
  phone text,
  address text,
  cost_base numeric(12,2),
  created_at timestamptz default now()
);

CREATE INDEX IF NOT EXISTS suppliers_tenant_idx
  ON public.suppliers (tenant_slug);

ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "suppliers read" ON public.suppliers;
CREATE POLICY "suppliers read"
ON public.suppliers
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = suppliers.tenant_slug
  )
);

DROP POLICY IF EXISTS "suppliers insert" ON public.suppliers;
CREATE POLICY "suppliers insert"
ON public.suppliers
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = suppliers.tenant_slug
  )
);

DROP POLICY IF EXISTS "suppliers update" ON public.suppliers;
CREATE POLICY "suppliers update"
ON public.suppliers
FOR UPDATE
USING (
  EXISTS (
    SELECT 1
    FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = suppliers.tenant_slug
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = suppliers.tenant_slug
  )
);

DROP POLICY IF EXISTS "suppliers delete" ON public.suppliers;
CREATE POLICY "suppliers delete"
ON public.suppliers
FOR DELETE
USING (
  EXISTS (
    SELECT 1
    FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = suppliers.tenant_slug
  )
);
