-- Histórico de redirecionamentos de tarefas

CREATE TABLE IF NOT EXISTS public.task_reassignments (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  tenant_slug text not null,
  department text,
  from_assignee text,
  to_assignee text,
  changed_by uuid null,
  changed_at timestamptz default now()
);

CREATE INDEX IF NOT EXISTS task_reassignments_task_id_idx
  ON public.task_reassignments (task_id);

CREATE INDEX IF NOT EXISTS task_reassignments_tenant_idx
  ON public.task_reassignments (tenant_slug);

ALTER TABLE public.task_reassignments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "task_reassignments read" ON public.task_reassignments;
CREATE POLICY "task_reassignments read"
ON public.task_reassignments
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = task_reassignments.tenant_slug
  )
);

DROP POLICY IF EXISTS "task_reassignments insert" ON public.task_reassignments;
CREATE POLICY "task_reassignments insert"
ON public.task_reassignments
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.user_tenants ut
    WHERE ut.user_id = auth.uid()
      AND ut.tenant_slug = task_reassignments.tenant_slug
  )
);
