-- Drafts por tarefa e departamento

CREATE TABLE IF NOT EXISTS public.task_drafts (
  id bigint generated by default as identity primary key,
  tenant_slug text not null,
  task_id bigint not null references public.tasks(id) on delete cascade,
  department text not null,
  state jsonb not null,
  updated_at timestamptz default now(),
  created_by uuid null,
  unique (tenant_slug, task_id, department)
);

CREATE INDEX IF NOT EXISTS task_drafts_tenant_idx
  ON public.task_drafts (tenant_slug);

CREATE INDEX IF NOT EXISTS task_drafts_task_idx
  ON public.task_drafts (task_id);
