CREATE TABLE IF NOT EXISTS public.task_assignments (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  tenant_slug text not null,
  department text not null,
  assignee text not null,
  role text not null default 'owner',
  assigned_by uuid null,
  created_at timestamptz default now(),
  unique (task_id, assignee, role)
);

CREATE INDEX IF NOT EXISTS task_assignments_task_id_idx
  ON public.task_assignments (task_id);

CREATE INDEX IF NOT EXISTS task_assignments_tenant_idx
  ON public.task_assignments (tenant_slug);
