-- API keys por tenant (uso exclusivo do backend/service role)
CREATE TABLE IF NOT EXISTS public.tenant_api_keys (
  id bigint generated by default as identity primary key,
  tenant_slug text not null,
  provider text not null,
  api_key text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (tenant_slug, provider)
);

CREATE INDEX IF NOT EXISTS tenant_api_keys_tenant_idx
  ON public.tenant_api_keys (tenant_slug);

ALTER TABLE public.tenant_api_keys ENABLE ROW LEVEL SECURITY;

-- Nega acesso por padrão. Service role ignora RLS.
CREATE POLICY "no select by clients" ON public.tenant_api_keys
  FOR SELECT USING (false);

CREATE POLICY "no insert by clients" ON public.tenant_api_keys
  FOR INSERT WITH CHECK (false);

CREATE POLICY "no update by clients" ON public.tenant_api_keys
  FOR UPDATE USING (false);

CREATE POLICY "no delete by clients" ON public.tenant_api_keys
  FOR DELETE USING (false);

-- Atualiza updated_at automaticamente
CREATE OR REPLACE FUNCTION public.set_tenant_api_keys_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_tenant_api_keys_updated_at ON public.tenant_api_keys;
CREATE TRIGGER trg_tenant_api_keys_updated_at
BEFORE UPDATE ON public.tenant_api_keys
FOR EACH ROW EXECUTE FUNCTION public.set_tenant_api_keys_updated_at();
