CREATE TABLE IF NOT EXISTS public.tenant_context (
  id bigint generated by default as identity primary key,
  tenant_slug text not null,
  source_path text not null,
  content text not null,
  is_binary boolean not null default false,
  content_type text,
  size_bytes integer,
  updated_at timestamptz default now(),
  unique (tenant_slug, source_path)
);

CREATE INDEX IF NOT EXISTS tenant_context_tenant_slug_idx
  ON public.tenant_context (tenant_slug);
