import pandas as pd

# Lista atualizada com URLs
produtos = [
    ("Saúde", "Vitamina D", "https://treelifepharmah.com.br/produto/vitamina-d/"),
    ("Saúde", "Vitalife", "https://treelifepharmah.com.br/produto/vitalife/"),
    ("Saúde", "Vita Forti BD Plus", "https://treelifepharmah.com.br/produto/vita-forti-bd-plus/"),
    ("Saúde", "Vinagre de maçã em cápsulas", "https://treelifepharmah.com.br/produto/vinagre-de-maca-em-capsulas/"),
    ("Saúde", "Ultra D", "https://treelifepharmah.com.br/produto/ultra-d/"),
    ("Saúde", "Ubiqsome", "https://treelifepharmah.com.br/produto/ubiqsome/"),
    ("Saúde", "TWK10 30 bilhões", ""),
    ("Saúde", "Sleep Balance", "https://treelifepharmah.com.br/produto/sleep-balance/"),
    ("Saúde", "Sirt Control", ""),
    ("Saúde", "Repositor de Eletrólitos", ""),
    ("Saúde", "Própolis Nasal", ""),
    ("Saúde", "Probióticos para prevenção de candidíase", ""),
    ("Saúde", "Pré-treino", ""),
    ("Saúde", "Phenibut", ""),
    ("Saúde", "Peptistrong", "https://treelifepharmah.com.br/produto/peptistrong/"),
    ("Saúde", "Oli‑Ola", ""),
    ("Saúde", "Nutrition Celular Balance", "https://treelifepharmah.com.br/produto/nutrition-celular-balance/"),
    ("Saúde", "Nutrem Capilar", "https://treelifepharmah.com.br/produto/nutrem-capilar/"),
    ("Saúde", "Metabolaid", ""),
    ("Saúde", "Maxsolve", ""),
    ("Saúde", "Magnésio Treonato 500 mg", ""),
    ("Saúde", "Magnésio Quelato 500 mg", ""),
    ("Saúde", "Low Homocysteine", "https://treelifepharmah.com.br/produto/low-homocysteine/"),
    ("Saúde", "Lisina", ""),
    ("Saúde", "Interbooster", "https://treelifepharmah.com.br/produto/interbooster/"),
    ("Saúde", "Homocistêina‑Ferritina", ""),
    ("Saúde", "Greenselect", ""),
    ("Saúde", "Garlic – Alho encapsulado", ""),
    ("Saúde", "Fórmula para TDAH", ""),
    ("Saúde", "Fórmula da Beleza", ""),
    ("Saúde", "Esteatoten – Esteatose Hepática", ""),
    ("Saúde", "Disbiolife", "https://treelifepharmah.com.br/produto/disbiolife/"),
    ("Saúde", "Diglothin", ""),
    ("Saúde", "Diabet Balance – Resistência Insulínica", ""),
    ("Saúde", "Creatina em sachê", ""),
    ("Saúde", "Creatina", ""),
    ("Saúde", "Creamelo", "https://treelifepharmah.com.br/produto/creamelo/"),
    ("Saúde", "Colágeno Verisol sachê", ""),
    ("Saúde", "Colágeno Verisol", ""),
    ("Saúde", "Colágeno Hidrolisado sachê", "https://treelifepharmah.com.br/produto/colageno-hidrolisado-sache/"),
    ("Saúde", "Colágeno Hidrolisado", ""),
    ("Saúde", "Coenzima Q10 100 mg", ""),
    ("Saúde", "Clonapure®", ""),
    ("Saúde", "Chá Calm Sleep", ""),
    ("Saúde", "Centella Asiática extrato seco", ""),
    ("Saúde", "Castanha da Índia 250 mg", ""),
    ("Saúde", "Castanha da Índia", ""),
    ("Saúde", "Ashwagandha", ""),
    ("Saúde", "Ansiless", ""),
    ("Saúde", "Adaptógeno Matinal", ""),
    ("Hair Care", "Beauty Hair Goma", "https://treelifepharmah.com.br/produto/beauty-hair-goma/"),
    ("Ômega 3", "Promo Ômega 3 Neural", "https://treelifepharmah.com.br/produto/promo-omega-3-neural/"),
    ("Ômega 3", "Ômega 3 Neural", "https://treelifepharmah.com.br/produto/omega-3-neural/"),
    ("Anti Ressaca", "UP! Anti Ressaca", "https://treelifepharmah.com.br/produto/up-anti-ressaca/"),
    ("Emagrecimento", "Akkermat®", "https://treelifepharmah.com.br/produto/akkermat/"),
    ("Emagrecimento", "Block Carb", ""),
    ("Emagrecimento", "Burnkcal", ""),
    ("Skin Care", "Anti Rugas Treelife Pharmah", ""),
    ("Skin Care", "Ácido Mandélico", "https://treelifepharmah.com.br/produto/acido-mandelico/")
]

df = pd.DataFrame(produtos, columns=["Categoria", "Produto", "URL"])
df.to_excel("/mnt/data/treelife_produtos_completo_atualizado.xlsx", index=False)
print("Feito!")
